fix: demote browser export
remix-run/web-std-io pull request #11
Opened 2022-06-06 20:35 UTC by penx

Prefer require, import and types exports over browser.

Exports are resolved in order, i.e. the first match is used.

I'm not sure why the browser export is using the raw src, however this causes issues with Jest when configured with jsdom, as it will resolve to this file and not be able to transpile it. Jest also throws a type error as discussed on https://github.com/remix-run/remix/issues/3402

2022-06-06 20:49 UTC, MichaelDeBoey requested changes

2022-06-06 20:49 UTC, MichaelDeBoey commented on packages/fetch/package.json
> +      "browser": "./src/lib.js"
`types` should come first according to [Community Conditions Definitions](https://nodejs.org/api/packages.html#community-conditions-definitions) docs

https://nodejs.org/api/packages.html#community-conditions-definitions

```suggestion
      "types": "./dist/src/lib.node.d.ts",
      "require": "./dist/lib.node.cjs",
      "import": "./src/lib.node.js",
      "browser": "./src/lib.js"
```

2022-06-06 21:29 UTC, MichaelDeBoey approved these changes

2022-06-06 21:30 UTC, MichaelDeBoey commented
CC/ @chaance @jacob-ebey @mjackson
Since I can't add you as a reviewer (I don't have any permissions on this repo), I wanted to tag you guys.

2022-11-17 08:14 UTC, JRasmusBm commented
I've been digging for over two hours and this is clearly the fix. Is there any progress on this PR? :innocent:

2023-07-19 03:09 UTC, nitrog7 commented
nudge

2023-07-19 17:15 UTC, brophdawg11 commented
> Exports are resolved in order, i.e. the first match is used.

Is there a source/reference for this?

2023-07-19 17:31 UTC, penx commented
> > Exports are resolved in order, i.e. the first match is used.
> 
> Is there a source/reference for this?



> Within the ["exports"](https://nodejs.org/api/packages.html#exports) object, key order is significant. During condition matching, earlier entries have higher priority and take precedence over later entries. The general rule is that conditions should be from most specific to least specific in object order.

https://nodejs.org/api/packages.html#conditional-exports

2023-07-19 17:59 UTC, jacob-ebey approved these changes

2023-07-19 18:05 UTC, jacob-ebey commented
I don't believe this is "the fix" everyone is after here. Generally, any non-standard conditions like "browser" are put above the "require", "import", and "default" conditions. Reasoning being some bundlers (like esbuild) don't allow you to disable the default conditions, and instead configure conditions to check before the defaults. 

This honestly sounds like a Jest issue of loading the wrong conditions for where they are executing. You aren't actually running Jest in the browser, so they should not be attempting to load the browser condition.

2023-07-19 18:14 UTC, brophdawg11 commented
Thanks @penx!  I missed that when I looked through those docs.

I agree with @jacob-ebey here - that snippet sounds to me like `browser` belongs _above_ `import`/`require` as it's more specific. Just like `node` should be above per the docs.

It does feel like Jest either (1) should not pick up the `browser` entry or (2) should handle ESM due to `type:module`.

I think we should split off the moving `types` to the top into a new Pr and merge that since that feels cut and dry.  Moving browser around feels wrong and likely requires some more investigation into exactly why jest can't handle it correctly.

2023-08-01 20:00 UTC, brophdawg11 commented
Extracted the lifting of `types` to the top into https://github.com/remix-run/web-std-io/pull/38

2023-08-22 19:39 UTC, MichaelDeBoey commented
Instead of demoting the `browser` export, we should provide a CJS version for browser as well, which is exactly what I did in #43

2023-09-01 16:06 UTC, closed without merging